mysite/Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'
urlpatterns = [
     path('summary/', views.cart_summary, name='cart_summary'),
     path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
     path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
     path('process_quantity/', views.process_quantity, name='process_quantity'),
] 

mysite/blog/urls.py
from django.urls import path
from . import views
from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, AddCategoryView, CategoryView, CategoryListView, LikeView
 
app_name = 'blog'
urlpatterns = [
    path('blog_home/', HomeView.as_view(), name="blog_home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='edit_post'),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name='delete_post'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('category-list/', CategoryListView, name='category-list'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('article/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('remove-comment/<int:pk>/', views.remove_comment, name='remove-comment'),
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from shop import views as auth_views


app_name='mysite'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('blog/',include('blog.urls')),
    path('payment/',include('payment.urls')),
    path('cart/',include('Cart.urls')),
    path('login/', auth_views.login_user, name='login'),
    path('logout/', auth_views.logout_user, name='logout'),
    path('register/', auth_views.register_user, name='register'),
    path("ckeditor5/", include('django_ckeditor_5.urls')),   
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) 

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from django_ckeditor_5.fields import CKEditor5Field

class Category(models.Model):
	name = models.CharField(max_length=255)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		#return reverse('article-detail', args=(str(self.id)) )
		return reverse('blog:blog_home')


class Post(models.Model):
	title = models.CharField(max_length=255)
	header_image = models.ImageField(null=True, blank=True, upload_to="blog_images/")
	title_tag = models.CharField(max_length=255)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	body = CKEditor5Field(blank=True, null=True, config_name='extends')
	#body = models.TextField()
	post_date = models.DateField(auto_now_add=True)
	# category = models.CharField(max_length=255,)
	category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
	snippet = models.CharField(max_length=255)
	likes = models.ManyToManyField(User, related_name='blog_posts')

	def total_likes(self):
		return self.likes.count()

	def __str__(self):
		return self.title + ' | ' + str(self.author)

	def get_absolute_url(self):
		#return reverse('article-detail', args=(str(self.id)) )
		return reverse('blog:blog_home')


class Comment(models.Model):
	post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
	name = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '%s - %s' % (self.post.title, self.name)

mysite/blog/forms.py
#models.py
from django import forms
from .models import Post, Category, Comment
from django_ckeditor_5.widgets import CKEditor5Widget


# choices = Category.objects.values_list('name', flat=True)
# choice_list = [(item, item) for item in choices]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'title_tag', 'author', 'category', 'body', 'snippet', 'header_image')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'author'}),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            # 'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
			'category': forms.Select(attrs={'class': 'form-control'}),
            'body': CKEditor5Widget(attrs={'class': 'form-control django_ckeditor_5'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'}),
        }



class EditForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'title_tag', 'body', 'snippet')

		widgets = {
			'title': forms.TextInput(attrs={'class': 'form-control'}),
			'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
			#'author': forms.Select(attrs={'class': 'form-control'}),
			'body': CKEditor5Widget(attrs={'class': 'form-control django_ckeditor_5'}),				
			'snippet': forms.Textarea(attrs={'class': 'form-control'}),			
		}


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name','body')

		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'comment-name'}),
			'body': forms.Textarea(attrs={'class': 'form-control'}),	
		}

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category, Comment
from .forms import PostForm, EditForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, Http404
#def home(request):
#	return render(request, 'home.html', {})

def LikeView(request, pk):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		liked = False
	else:
		post.likes.add(request.user)
		liked = True
	
	return HttpResponseRedirect(reverse('blog:article-detail', args=[str(pk)]))

class HomeView(ListView):
	model = Post
	template_name = 'blog_home.html'
	cats = Category.objects.all()
	ordering = ['-post_date']
	#ordering = ['-id']

	def get_context_data(self, *args, **kwargs):
		cat_menu = Category.objects.all()
		context = super(HomeView, self).get_context_data(*args, **kwargs)
		context["cat_menu"] = cat_menu
		return context

def CategoryListView(request):
	cat_menu_list = Category.objects.all()
	return render(request, 'category_list.html', {'cat_menu_list':cat_menu_list})



def CategoryView(request, cats):
	category_posts = Post.objects.filter(category=cats.replace('-', ' '))
	cat_menu = Category.objects.all()
	return render(request, 'categories.html', {
		'cats':cats.replace('-', ' ').title(),
		 'category_posts':category_posts,
		 'cat_menu':cat_menu
		 })


class ArticleDetailView(DetailView):
	model = Post
	template_name = 'article_details.html'

	def get_context_data(self, *args, **kwargs):
		cat_menu = Category.objects.all()
		context = super(ArticleDetailView, self).get_context_data(*args, **kwargs)
		
		stuff = get_object_or_404(Post, id=self.kwargs['pk'])
		total_likes = stuff.total_likes()	
		
		liked = False
		if stuff.likes.filter(id=self.request.user.id).exists():
			liked = True

		context["cat_menu"] = cat_menu
		context["total_likes"] = total_likes
		context["liked"] = liked
		return context

class AddPostView(CreateView):
	model = Post
	form_class = PostForm
	template_name = 'add_post.html'
	#fields = '__all__'
	#fields = ('title', 'body')

def add_comment(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post_id = pk
            comment.save()
            return redirect('blog:article-detail', pk)
    else:
        form = CommentForm()

    context = {'form': form}
    return render(request, 'add_comment.html', context)

def remove_comment(request, pk):
    try:
        comment = Comment.objects.get(id=str(pk))
    except Comment.DoesNotExist:
        raise Http404("Comment does not exist")  # Optional: Handle 404 error in a custom way

    if request.method == 'POST':
        comment.delete()
        return redirect('blog:article-detail', pk=comment.post_id)
    
    context = {'comment': comment}
    return render(request, 'article_details.html', context)


class AddCategoryView(CreateView):
	model = Category
	#form_class = PostForm
	template_name = 'add_category.html'
	fields = '__all__'
	#fields = ('title', 'body')

class UpdatePostView(UpdateView):
	model = Post
	form_class = EditForm
	template_name = 'edit_post.html'
	#fields = ['title', 'title_tag', 'body']

class DeletePostView(DeleteView):
	model = Post
	template_name = 'delete_post.html'
	success_url = reverse_lazy('home')

mysite/blog/templates/add_category.html
{% extends 'base.html' %}
{% block title %}Create A New Blog Category!{% endblock %}
{% block content %}

    
{% if user.is_authenticated %}
	<h1>Add Category...</h1>
	<br/><br/>

	<div class="form-group m-4">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-secondary">Add Category</button>
		</form>
	</div>

{% else %}

You're not allowed here! (and you know it...)

{% endif %}



{% endblock %}

mysite/blog/templates/add_comment.html
{% extends 'base.html' %}
{% block title %}Comment On Blog Post{% endblock %}
{% block content %}

    

	<h1>Add Comment...</h1>
	<br/><br/>

	<div class="form-group">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-secondary">Add Comment</button>
		</form>
	</div>


{% endblock %}

mysite/blog/templates/add_post.html
{% extends 'base.html' %}


{% block content %}

{% if user.is_authenticated %} 

		<h1>Add Post...</h1>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.media }}
			{{ form.as_p }}
			<button class="btn btn-success" >Post</button>

			<a href="{% url 'blog:add_category' %}" class="btn btn-outline-primary">add category</a>

		<br/><br/>
		<script>
			var name = "{{ user.id }}";
			document.getElementById("author").value = name;
		</script>
{% else %}
You are not authorized to view this page...

{% endif %}

{% endblock %}

mysite/blog/templates/article_details.html
{% extends 'base.html' %}


{% block content %}

<body class="container-fluid">
	<h1 class="text-center">{{post.title}}</h1>
    <article class="m-3 p-2 shadow-lg">
        <div class="d-flex justify-content-between" >
            <div class="text-center">
                <p class="fw-medium"><small class="fw-lighter mx-2 d-flex">By: {{ post.author }}</small>  Published: {{ post.post_date }} </p>
            </div>
            <div>
                <form action="{% url 'blog:like_post' post.pk %}" method="POST">
                    {% csrf_token %}
                
                {% if user.is_authenticated %}
                    {% if liked %}
                        <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-danger btn-sm">Unlike</button> 
                    {% else %}	
                        <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm">Like</button> 
            
                    {% endif %}
                {% else %}
                    <small><a href="{% url 'login' %}">Login</a>to like</small>
                {% endif %}
                <span>{{ total_likes }} <small class="d-none">Likes</small> </span>    
                </form>
            </div>
        </div>
        
        {% if post.header_image %}
        <div class="d-flex justify-content-center position-sticky top-0 z-n1 shadow shadow-lg shadow-black bg-body-tertiary">
            <img src="{{ post.header_image.url }}" alt="">
        </div>
        {% endif %}
        <div class="d-flex justify-content-start m-1">
            <p class="fw-bold fs-3 text-primary-emphasis">Share on:</p>
            <div class="d-flex justify-content-between w-25 p-2">
                <a href="" id="twitter-x" class="d-flex flex-column align-items-center text-decoration-none m-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                    <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                  </svg>
                  <span class="text-black d-none d-md-inline">Twitter</span>
                </a>
                <a href="" id="facebook" class="d-flex flex-column align-items-center text-decoration-none m-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                  </svg>
                  <span class="text-black d-none d-md-inline">Facebook</span>
                </a>
                <a href="" id="instagram" class="d-flex flex-column align-items-center text-decoration-none m-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                  </svg>
                  <span class="text-black d-none d-md-inline">Instagram</span>
                </a>
                <a href="" id="tiktok" class="d-flex flex-column align-items-center text-decoration-none m-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-tiktok" viewBox="0 0 16 16">
                    <path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3z"/>
                  </svg>
                  <span class="text-black d-none d-md-inline">Tiktok</span>
                </a>
                <a href="" id="linkedin" class="d-flex flex-column align-items-center text-decoration-none m-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                  </svg>
                  <span class="text-black d-none d-md-inline">Linkedin</span>
                </a>
            </div>
        </div>

        <article class="bg-white text-body-emphasis p-1">
            {{ post.body|safe }}
        </article>
        <a href="{% url 'blog:blog_home' %}" class="btn btn-sm btn-outline-info" >
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-houses" viewBox="0 0 16 16">
                <path d="M5.793 1a1 1 0 0 1 1.414 0l.647.646a.5.5 0 1 1-.708.708L6.5 1.707 2 6.207V12.5a.5.5 0 0 0 .5.5.5.5 0 0 1 0 1A1.5 1.5 0 0 1 1 12.5V7.207l-.146.147a.5.5 0 0 1-.708-.708zm3 1a1 1 0 0 1 1.414 0L12 3.793V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v3.293l1.854 1.853a.5.5 0 0 1-.708.708L15 8.207V13.5a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 4 13.5V8.207l-.146.147a.5.5 0 1 1-.708-.708zm.707.707L5 7.207V13.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5V7.207z"/>
            </svg>
            Home
        </a>
    </article>

    {% if user.is_superuser %}
        {% if user.id == post.author.id %}
        <!-- delete and edit -->
        <div class="d-flex justify-content-between mx-3">
            <a href="{% url 'blog:edit_post' post.pk %}" class="btn btn-success">Edit Post</a>
            <a href="{% url 'blog:delete_post' post.pk %}" class="btn btn-success">Delete</a>
        </div>
        {% endif %}
    {% endif %}

    <!-- comments section -->
     <div class="border border-1 border-dark m-2 p-2 rounded-4">
        <h4 class="fw-bold m-1 text-primary-emphasis">Comments</h4>
        {% if not post.comments.all %}
            No Comments Yet...<a href="{% url 'blog:add_comment' post.pk %}">Add One</a>
        {% else %}
        <a href="{% url 'blog:add_comment' post.pk %}">Add Comment</a>
        <br/><br/>

            {% for comment in post.comments.all %}
            <div>
                <div>
                    <p class="p-0 m-0"> Comment by:
                        <strong class="">
                            {{ comment.name }}  
                        </strong>
                    </p>
                    <small class="">
                        {{ comment.date_added }}
                    </small>
                    <p>{{ comment.body }}</p>   
                </div>
                <div>
                    <form action="{% url 'blog:remove-comment' comment.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-small btn-outline-secondary" > remove</button>
                    </form>
                </div>
                <hr>
            </div>    
            {% endfor %}
                    <a href="{% url 'blog:add_comment' post.pk %}">Add Comment</a>
            {% endif %}
            <br/>
     </div>

</body>
{% endblock %}

mysite/blog/templates/blog_home.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Home</title>
</head>
<body class="">
    <div class="row m-1 bg-light">
        <div class="container col-12 col-md-4 col-lg-4">
            <div class="bg-primary">
                <h3 class="p-2 text-white">Blog Category</h3>
            </div>
            <ul class="text-black list-unstyled bg-dark-subtle">
                {% for post in cat_menu %}
                <li class=""><a href="{% url 'blog:category' post.name %}" class="text-decoration-none text-primary-emphasis fw-bolder m-1">{{ post.name }}</a></li>
                <hr>
                {% endfor %}
            </ul>
        </div>
        <div class="col-12 col-md-7 col-lg-7">
            <ul class="list-unstyled" >
                {% for post in object_list %}
                <li class="bg-white shadow-sm shadow-primary" >
                    <!-- <li><a href="{}">{{ post.title }}</a></li> -->
                     <!-- Post preview -->
                    <div class="post-preview d-flex">
                        {% if post.header_image %}
                        <div>
                            <img src="{{ post.header_image.url }}" alt="" style="height: 20vh;">
                        </div>
                        {% endif %}
                        <div>
                            <a href="{% url 'blog:article-detail'  post.pk %}" class="text-decoration-none text-black">
                                <h2 class="post-title">{{ post.title }}</h2>- {{ post.category }}
                                <p class="post-subtitle fw-lighter fst-italic"> {{ post.snippet }} </p>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="#!" class="fw-lighter fst-italic text-decoration-none"> {{ post.author}} </a>
                                on {{ post.pub_date }}
                            </p>
                        </div>    
                    </div>
                </li>
                    <hr class="my-4">
                {% endfor %}
            </ul>
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'blog:add_post' %}" class="btn btn-success">Add post</a>
        {% endif %}    
    </div> 
</body>
</html>
{% endblock %}

mysite/blog/templates/categories.html
{% extends 'base.html' %}

{% block content %}
{% if category_posts %}
<body class="">
    <div class="row m-1 bg-light">
        <div class="container col-12 col-md-4 col-lg-4">
            <div class="bg-primary">
				<a href="{% url 'blog:blog_home' %}" class="text-decoration-none" ><h3 class="p-2 text-white">Blog Category</h3></a> 
            </div>
            <ul class="text-black list-unstyled bg-dark-subtle">
                {% for post in cat_menu %}
                <li class=""><a href="{% url 'blog:category' post.name %}" class="text-decoration-none text-primary-emphasis fw-bolder m-1">{{ post.name }}</a></li>
                <hr>
                {% endfor %}
            </ul>
        </div>
        <div class="col-12 col-md-7 col-lg-7">
			<h2> {{ cats }} </h2>
            <ul>
                {% for post in category_posts %}
                    <!-- <li><a href="{}">{{ post.title }}</a></li> -->
                     <!-- Post preview -->
                    <div class="post-preview d-flex">
                        {% if post.header_image %}
                        <div>
                            <img src="{{ post.header_image.url }}" alt="" style="height: 20vh;">
                        </div>
                        {% endif %}
                        <div>
                            <a href="{% url 'blog:article-detail'  post.pk %}" class="text-decoration-none text-black">
                                <h2 class="post-title">{{ post.title }}</h2>- {{ post.category }}
                                <p class="post-subtitle fw-lighter fst-italic"> {{ post.snippet }} </p>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="#!" class="fw-lighter fst-italic text-decoration-none"> {{ post.author}} </a>
                                on {{ post.pub_date }}
                            </p>
                        </div>    
                    </div>
                    <hr class="my-4">
                {% endfor %}
            </ul>
        </div>
        {% if user.is_superuser %}
        <a href="{% url 'blog:add_post' %}" class="btn btn-success">Add post</a>
        {% endif %}    
    </div> 
</body>
{% else %}
	<h2>Sorry this page does not exist...</h2>
{% endif %}

{% endblock %}

mysite/blog/templates/category_list.html
{% extends 'base.html' %}
{% block title %}Blog Categories{% endblock %}



{% block content %}

	<h1>Blog Categories</h1>
	{% for item in cat_menu_list %}
                <h4><a class="dropdown-item" href="{% url 'category' item|slugify %}">{{ item }}</a></h4>
        {% endfor %}


{% endblock %}

mysite/blog/templates/delete_post.html
{% extends 'base.html' %}


{% block content %}
{% if user.is_authenticated %} 
	{% if user.id == post.author.id %}
	
		<h1>Delete Post...</h1>

		<h4 class="m-4 fw-bold">Delete: {{ post.title}}</h4>
		<form method="POST" class="form-control">
			{% csrf_token %}
			<strong>Are you sure?!</strong><br/>
			<button>Delete Post</button>
		</form>
		<br/><br/>

	{% else %}
		You are not authorized to view this page...
	{% endif %}
{% else %}
	You are not authorized to view this page...
{% endif %}


{% endblock %}

mysite/blog/templates/edit_post.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %} 
	{% if user.id == post.author.id %}
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Edit Post</title>
        </head>
        <body>
            <h1>Edit Post</h1>
            <form method="post" class="form-control" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-primary">Update</button>
            </form>
        </body>
        <script>
            document.getElementById("id_title").classList.add("form-control");
            document.getElementById("id_body").classList.add("form-control");
        </script>

        </html>
    {% else %}
		You are not authorized to view this page...
	{% endif %}
{% else %}
	You are not authorized to view this page...
{% endif %}

{% endblock %}

mysite/blog/templates/remove_comment.html
{% extends 'base.html' %}
{% block title %}Comment On Blog Post{% endblock %}
{% block content %}

    

	<h1>Add Comment...</h1>
	<br/><br/>

	<div class="form-group">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-secondary">Remove Comment</button>
		</form>
	</div>
	<script>
		var name = "{{ user.id }}";
		document.getElementById("comment-name").value = name;
	</script>


{% endblock %}