mysite/Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'
urlpatterns = [
     path('summary/', views.cart_summary, name='cart_summary'),
     path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
     path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
     path('process_quantity/', views.process_quantity, name='process_quantity'),
] 

mysite/blog/urls.py
from django.urls import path
from . import views
from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, AddCategoryView, CategoryView, CategoryListView, LikeView
 
app_name = 'blog'
urlpatterns = [
    path('blog_home/', HomeView.as_view(), name="blog_home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='edit_post'),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name='delete_post'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('category-list/', CategoryListView, name='category-list'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('article/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('remove-comment/<int:pk>/', views.remove_comment, name='remove-comment'),
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from shop import views as auth_views


app_name='mysite'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('blog/',include('blog.urls')),
    path('payment/',include('payment.urls')),
    path('cart/',include('Cart.urls')),
    path('login/', auth_views.login_user, name='login'),
    path('logout/', auth_views.logout_user, name='logout'),
    path('register/', auth_views.register_user, name='register'),
    path("ckeditor5/", include('django_ckeditor_5.urls')),   
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) 

mysite/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'
urlpatterns = [
    path('payment_success/', views.payment_success, name = 'payment_success'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_processing/', views.process_order, name='process_order'),
    path('undelivered_dash', views.undelivered_dash, name='undelivered_dash'),
    path('delivered_dash/', views.delivered_dash, name='delivered_dash'),
    path('orders/<int:pk>', views.view_order, name='view_order'),
    path('access_token/', views.access_token, name='access_token'),
    path('stk-push/', views.stk_push, name='stk_push')
]

mysite/shop/urls.py
from django.urls import path
from . import views


app_name='shop'
urlpatterns = [
    path('',views.home, name = 'home'),
    path('product/<int:pk>', views.product, name = "product"),
    path('category/<str:cat>', views.category, name = "category"),
    path('offers/', views.offers, name = "offers"),
    path('condition/<str:cat>', views.condition, name = "condition"),
    # path('sub_category/<str:cat>', views.sub_category, name = "sub_category"),
    path('update_user/', views.update_user, name='update_user'),
    path('update_password/', views.update_password, name='update_password'),
    path('update_info/', views.update_info, name='update_info'),
    path('search/', views.search, name='search'),
    path('account_info/', views.account_info, name='account_info'),
    path('product/<int:pk>/add_review', views.add_review, name='add_review'),
    path('product/<int:pk>/remove_review', views.remove_review, name='remove_review'),
    path('favourites/', views.favourites, name='favourites'),
    path('process_email/', views.process_email, name='process_email'),
] 

mysite/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect, Http404

from .models import Product, Category, Condition, Profile, Sub_category, Brand, Like, Review, Email
from .filters import ProductFilter

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm, SetPasswordForm
from .forms import SignUpForm, UpdateUserForm, ChangePasswordForm, UserInfoForm, LoginForm, ReviewForm
from django import forms

from payment.forms import ShippingForm
from payment.models import ShippingAddress

from Cart.cart import Cart

from django.db.models import Q

# Create your views here.

def search(request):
    if request.method == "POST":
        searched = request.POST.get('searched', '')  # Safely get the search term from POST data

        if searched:
            # Query the database for matching products
            products = Product.objects.filter(
                Q(name__icontains=searched) | Q(description__icontains=searched)
            )

            if products.exists():
                return render(request, 'search.html', {
                    'searched': products,  # Pass the actual products to the template
                })
            else:
                messages.success(request, "No products found matching the search criteria.")
        else:
            messages.error(request, "Please enter a search term.")

        # Always redirect to home page after POST request processing
        return redirect('shop:home')

    # Handle GET requests or unexpected scenarios by redirecting to home
    return redirect('shop:home')

def home(request):
    products = Product.objects.all()
    return render(request, 'home.html', {
        'products':products,
    })

def offers(request):
    # Filter products with a discount greater than 0
    products = Product.objects.filter(discount__gt=0)
    # Filter brands based on the selected brands
    selected_brands = request.POST.getlist('brands')
    if selected_brands:
        products = products.filter(brand__id__in=selected_brands)
    # Retrieve distinct brands
    brands = Brand.objects.distinct()
    return render(request, 'offers.html', {
        'products': products,
        'brands': brands,
        'selected_brands': selected_brands,
    })


def account_info(request):
    return redirect("shop:update_info")

# def product(request,pk):
#     product = Product.objects.get(id = pk)
#     return render(request, 'product.html', {
#         'product':product,
#     })
def product(request, pk):
    product = get_object_or_404(Product, id=pk)
    liked = False

    if request.user.is_authenticated:
        # Check if the user has already liked this product
        liked = Like.objects.filter(user=request.user, product=product).exists()

    if request.method == 'POST':
        # Handle like/unlike button click
        if liked:
            Like.objects.filter(user=request.user, product=product).delete()
        else:
            Like.objects.create(user=request.user, product=product)

        # Redirect back to the product page
        return redirect('shop:product', pk)

    return render(request, 'product.html', {
        'product': product,
        'liked': liked,
    })

def favourites(request):
    user_likes = Like.objects.filter(user=request.user)
    liked_products = [like.product for like in user_likes]

    return render(request, 'liked_page.html', {'liked_products': liked_products})

def add_review(request, pk):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product_id = pk
            review.save()
            # return redirect('shop:home')  # Replace 'home' with your actual URL name
            return redirect('shop:product', pk=review.product_id)
    else:
        form = ReviewForm()

    return render(request, 'add_review.html', {'form': form})


def remove_review(request, pk):
    try:
        review = Review.objects.get(id=str(pk))
    except Review.DoesNotExist:
        raise Http404("Review does not exist")  # Optional: Handle 404 error in a custom way

    if request.method == 'POST':
        review.delete()
        return redirect('shop:product', pk=review.product_id)
        # return redirect('shop:home')
    
    context = {'review': review}
    return render(request, 'product.html', context)



from django.db.models import Max, Min

def category(request, cat):
    cat = cat.replace('-', ' ')
    try:
        category_obj = Category.objects.get(name=cat)
        products = Product.objects.filter(category=category_obj)
        sub_categories = Sub_category.objects.filter(category=category_obj)
        brands = Brand.objects.filter(product__category=category_obj).distinct()

        # Handling brand and sub-category filtering
        selected_brands = request.POST.getlist('brands')
        selected_sub_categories = request.POST.getlist('sub_categories')

        if selected_brands:
            products = products.filter(brand__id__in=selected_brands)

        if selected_sub_categories:
            products = products.filter(sub_category__id__in=selected_sub_categories)

        # Get Max and Min Value of Queryset
        max_price = products.aggregate(Max('price'))['price__max']
        min_price = products.aggregate(Min('price'))['price__min']
        
        # Split the range into 4 (adjust as needed)
        range_step = (max_price - min_price) / 4

        return render(request, 'category.html', {
            'products': products,
            'category': category_obj,
            'sub_categories': sub_categories,
            'brands': brands,
            'selected_brands': [int(b) for b in selected_brands],
            'selected_sub_categories': [int(sc) for sc in selected_sub_categories],
            'min_price': min_price,
            'max_price': max_price,
            'range_step': range_step,
        })

    except Category.DoesNotExist:
        return redirect('shop:home')


def condition(request, cat):
    cat = cat.replace('-', ' ')
    try:
        condition = Condition.objects.get(name = cat)
        products = Product.objects.filter(condition = condition,)
        brands = Brand.objects.filter(product__condition=condition).distinct()

        # Handling brand filtering
        selected_brands = request.POST.getlist('brands')

        if selected_brands:
            products = products.filter(brand__id__in=selected_brands)

        # Get Max and Min Value of Queryset
        max_price = products.aggregate(Max('price'))['price__max']
        min_price = products.aggregate(Min('price'))['price__min']
        
        # Split the range into 4 (adjust as needed)
        range_step = (max_price - min_price) / 4

        return render(request, 'condition.html', {
            'products': products,
            'condition': condition,
            'brands': brands,
            'selected_brands': [int(b) for b in selected_brands],
            'min_price': min_price,
            'max_price': max_price,
            'range_step': range_step,
        })

    except Condition.DoesNotExist:
        return redirect('shop:home')
        
from django.urls import reverse

def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user: #is not None:
                login(request, user)
                # Redirect to the next URL after login, or to 'shop:home' if not set
                # next_url = request.GET.get('next', 'shop:home')
                messages.success(request, "You have been logged in.")
                # return redirect(next_url)
                return redirect('shop:home')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

from django.contrib.auth.decorators import login_required

def update_password(request):
	if request.user.is_authenticated:
		current_user = request.user
		# Did they fill out the form
		if request.method  == 'POST':
			form = ChangePasswordForm(current_user, request.POST)
			# Is the form valid
			if form.is_valid():
				form.save()
				messages.success(request, "Your Password Has Been Updated...")
				login(request, current_user)
				return redirect('login')
			else:
				for error in list(form.errors.values()):
					messages.error(request, error)
					return redirect('shop:update_password')
		else:
			form = ChangePasswordForm(current_user)
			return render(request, "update_password.html", {'form':form})
	else:
		messages.success(request, "You Must Be Logged In To View That Page...")
		return redirect('shop:home')



def update_info(request):
    # current_user = request.user
    current_user = Profile.objects.get(user__id=request.user.id)

    # Try to get the user's profile; create one if it doesn't exist
    # current_profile, created = Profile.objects.get_or_create(user=current_user)
    shipping_user, created = ShippingAddress.objects.get_or_create(user_id=request.user.id)

    if request.method == 'POST':
        u_form = UserInfoForm(request.POST, instance=current_user)
        s_form = ShippingForm(request.POST, instance = shipping_user)
        if u_form.is_valid():
            # saving info form
            u_form.save()   

mysite/shop/templates/account_info.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <div class=" d-flex flex-column flex-sm-shrink-5 p-3 bg-light" style="width: 280px; height: 100vh;" id="nav">
        <a href="" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
          <span class="fs-4 fw-bold">Account</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="/" class="nav-link active" aria-current="page">
              Home
            </a>
          </li>
          <li>
            <a href="{% url 'shop:update_user' %}" class="nav-link link-dark">
              Profile
            </a>
          </li>
          <li>
            <a href="{% url 'shop:update_password' %}" class="nav-link link-dark">
              Change Password
            </a>
          </li>
          <li>
            <a href="{% url 'shop:update_info' %}" class="nav-link link-dark">
              Delivery
            </a>
          </li>
          <li>
            <a href="{% url 'shop:favourites' %}" class="nav-link link-dark">
              Wishlist
            </a>
          </li>
          {% if user.is_superuser %}
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <!-- <li class="nav-item">
                <a href="#" class="nav-link active" aria-current="page">
                    Orders
                </a>
                </li> -->
                <li class="nav-item dropdown">
                  <button class="nav-link dropdown-toggle" href="" id="navbar" role="button" data-bs-toggle="dropdown" aria-expanded="True">
                    Orders
                  </button>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbar">
                    <li><a class="dropdown-item" href="{% url 'payment:delivered_dash' %}">Delivered</a></li>
                    <li><a class="dropdown-item" href="{% url 'payment:undelivered_dash' %}">Un-Delivered</a></li>
                    <!-- <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                  </ul>
                </li>
                <li>
                <a href="#" class="nav-link link-dark">
                    Admin
                </a>
                </li>
                <li>
                    <a href="#" class="nav-link link-dark">
                    Other
                    </a>
                </li>
            </ul>
            {% endif %}
        </ul>
        <hr>
        <div class="dropdown">
          <a href="{% url 'logout' %}" class="d-flex align-items-center link-dark text-decoration-none" >
            <strong class="btn btn-success">Logout</strong>
          </a>
          <!-- <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
            <li><a class="dropdown-item" href="#"></a></li>
            <li><a class="dropdown-item" href="#"></a></li>
            <li><a class="dropdown-item" href="#"></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#"></a></li>
          </ul> -->
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

mysite/shop/templates/navbar.html
{% load static %}
{% load custom_tags %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!--Navigation-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <nav class="navbar bg-light navbar-expand-lg z-0 p-0">
        <div class="container-fluid">
            <button class="navbar-toggler border-0 p-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas navbar-offcanvas offcanvas-start" tabindex="-1" data-bs-backdrop="false" data-bs-scroll="true" id="main-nav">
              <button type="button" class="btn-close text-reset d-lg-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              <div class="offcanvas-body">
                <ul class="navbar-nav nav-tabs justify-content-start flex-grow-1 pe-3">
                  <!--shop by Category-->
                    <li class="nav-item">
                        <div class="btn-group dropend justify-content-between btn-b">
                          <a href="" class="nav-link"  onclick="toggleDropdown(event)" role="button">Shop by Category</a>
                          <ul class="dropdown-menu border-1 border-primary position-absolute top-100" id="navDropdown">
                            {% get_categorys as categorys %}
                            {% for category in categorys %}
                            <li class=""><a href="{% url 'shop:category' category.name %}" class="dropdown-item">{{ category.name }}</a></li>
                            {% endfor %}
                          </ul>
                        </div>
                    </li>
                    <!--shop by Condition-->
                    <li class="nav-item">
                        <div class="btn-group dropend justify-content-between btn-b">
                          <a href="" class="nav-link" onclick="toggleDropdown1(event)">Shop by Condition</a>
                          <ul class="dropdown-menu border-1 border-primary position-absolute top-100" id="navDropdown1">
                            {% get_conditions as conditions %}
                            {% for condition in conditions %}
                            <li class=""><a href="{% url 'shop:condition' condition.name %}" class="dropdown-item">{{ condition.name }}</a></li>
                            {% endfor %}
                            <!-- <li class=""><a href="{% url 'shop:condition' 'condition2' %}" class="dropdown-item">Pain Relievers</a></li>
                            <li class=""><a href="" class="dropdown-item">Bone,Joints and Muscle</a></li>                                           
                            <li class=""><a href="" class="dropdown-item">Eye Care</a></li>
                            <li class=""><a href="" class="dropdown-item">Ear Care</a></li>
                            <li class=""><a href="" class="dropdown-item">Oral Care</a></li>
                            <li class=""><a href="" class="dropdown-item">Cold,flu and Cough</a></li>
                            <li class=""><a href="" class="dropdown-item">Brain and Nervous Disorder</a></li>
                            <li class=""><a href="" class="dropdown-item">Diabetes</a></li>
                            <li class=""><a href="" class="dropdown-item">Reproductive</a></li>
                            <li class=""><a href="" class="dropdown-item">Hypertension</a></li>
                            <li class=""><a href="" class="dropdown-item">Endocrine Disorders</a></li>
                            <li class=""><a href="" class="dropdown-item">Allergies</a></li>
                            <li class=""><a href="" class="dropdown-item">Bacterial,Fungal and Protozoal infections</a></li>
                            <li class=""><a href="" class="dropdown-item">STD's</a></li> -->
                          </ul>
                        </div>
                    </li>
                    <!--Health Center-->
                    <li class="nav-item">
                        <div class="btn-group dropend justify-content-between btn-b">
                          <a href="" class="nav-link">Health Center</a>
                          <!-- <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropend</span>
                          </button>
                          <ul class="dropdown-menu border-1 border-primary bg-success">
                            <li class=""><a href="#" class="dropdown-item fw-semibold">Chronic illnesses</a></li>
                            <li class=""><a href="#" class="dropdown-item fw-semibold">Asthma</a></li>
                            <li class=""><a href="#" class="dropdown-item fw-semibold">Skin Care</a></li>
                            <li class=""><a href="#" class="dropdown-item fw-semibold">Sexuall Wellness</a></li>
                            <li class=""><a href="#" class="dropdown-item fw-semibold">Self Diagnos kits</a></li>
                            <li class=""><a href="#" class="dropdown-item fw-semibold">Mother and Baby</a></li>
                          </ul> -->
                        </div>
                    </li>
                    <!--Offers-->
                    <li class="nav-item bg-warning">                                      
                      <a href="{% url 'shop:offers' %}" class="nav-link fw-bolder text-primary">Offers</a>
                    </li>
                    <!--Submit Prescription-->
                    <li class="nav-item">
                        <a class="nav-link" href="">Submit prescription</a>
                    </li>
                </ul>
                <!--Delivery Location-->
                <div class="btn btn-outline-primary">
                  <a href="{% url 'shop:update_info' %}" class="text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                      <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10m0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/>
                    </svg>
                    <span class="fw-bold text-success">Delivery Location</span>
                  </a>                                 
                </div>
              </div>
            </div>
        </div> 
    </nav>
    <script>
      function toggleDropdown(event) {
        event.preventDefault();
        const dropdownContent = document.getElementById("navDropdown");
        dropdownContent.classList.toggle("show");
      }
      function toggleDropdown1(event) {
        event.preventDefault();
        const dropdownContent = document.getElementById("navDropdown1");
        dropdownContent.classList.toggle("show");
      }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

mysite/shop/templates/offercard.html
{% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
<div class="d-inline m-1 col-4 col-lg-2 carousel-item active p-0" id="carousel-item" style="width: fit-content;">
    <div class="card p-0 m-0" style="width: 10rem;">
      <div class="" style="height: 7rem;">
        <span class="fw-light bg-primary-subtle position-absolute top-0 start-0">-ksh{{product.discount}} </span>
        <img src=" {{product.image.url}} " class="card-img-top image-fluid" alt="Item Image" style="height: 25vh;">
      </div>
      <div class="card-body d-inline-block">
        <h5 class="card-title">{{ product.name }} </h5>
        <p class="card-text m-1 w-100"><span class="text-muted text-decoration-line-through">ksh{{product.price}} </span>ksh{{product.new_price}}</p>
        <p class="card-text m-0 p-0">Discounted Price</p>
        <div class="p-0 m-0">
          <!-- <button type="button" value="{{ product.id }}" data-product-id="{{ product.id }}" id="add-cart" class="btn btn-primary m-1 container-fluid p-0">+ cart</button> -->
          <form action="{% url 'Cart:add_to_cart' product.id %}" method="post" class="container-fluid p-0">
            {% csrf_token %}
            <input type="submit" value="+ cart" class="btn btn-primary container-fluid p-0">
          </form>
          <a href="{% url 'shop:product' product.id %}" class="btn btn-secondary m-1 container-fluid p-0">view item</a>
        </div>
      </div>
    </div> 
  </div> 

mysite/shop/templates/search.html
{% extends 'base.html' %}

{% block content %}
<main class="col-12 col-lg-9 d-block mx-0 px-0">
    <h2 class="text-center text-primary-emphasis">Search Results</h2>
    <div class="d-flex flex-wrap" id="card-container">
        {% for product in searched %}
            <div class="product-card">
                <h3>{{ product.name }}</h3>
                {% if product.discount > 0 %}
                    {% include 'offercard.html' with product=product %}                    
                {% else %}
                    {% include 'pricecard.html' with product=product %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

mysite/shop/templates/searchbar.html
<form method="POST" action="{% url 'shop:search' %}" class="w-100">
    {% csrf_token %}
    <div class="p-2 border border-black rounded-5 input-group d-flex m-2 align-items-center" style="display: inline;">
        <input autocomplete="off" placeholder="Search for products" type="search" class="border-0 m-0 p-0 form-control" style="width: 80%; height: 26px;" name="searched">
        <button class="btn align-items-center" style="height: 25px;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search position-absolute top-0 end-0" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
            </svg>
        </button>
    </div>
       
</form>

mysite/shop/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="./test">
</head>
<body>
    <div class="container">
        <form action="#" method="post">
            <div class="input_field"><label>username</label><input type="text"></div>
            <div class="input_field"><label>password</label><input type="password"></div>
            <div class="input_field"><label>email</label><input type="email"></div>
            <input type="button" value="Login">
        </form>
    </div>
</body>
</html>

mysite/shop/templates/update_user.html
{% extends 'base.html' %}

{% block content %}  
  <style>
        
    @media (min-width: 768px) {
        #form {
        width: 50vw;
        }
    }
    @media (max-width: 768px) {
        #form {
        width: 75vw;
        }
    }
    </style>
     <div>
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show position-absolute top-0" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}
<body class="container-fluid d-block">
<div class="d-flex" >
  <div class="d-inline-block mt-3" >
    {% include 'account_info.html' %}
  </div>

  <div class="text-center d-flex flex-column justify-content-center align-items-center mx-5 my-2">
    <h3 class="text-center text-primary fw-bold">User Profile</h3>      
    <form class="form-control" id="form" method="POST" action="{% url 'shop:update_user' %}">
        {% csrf_token %}

        {{ user_form.as_p }}
        
        
        <div class="d-flex justify-content-evenly">
          <button class="btn btn-lg btn-primary btn-block" type="submit">Change</button>
          <a href="{%  url 'shop:update_password' %}" class="btn">Change Password</a>
        </div>
        <p class="mt-5 mb-3 text-muted">© 2024</p>
    </form>
        
  </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </div>
</div>
  
  
</body>
{% endblock %}