mysite/Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'
urlpatterns = [
     path('summary/', views.cart_summary, name='cart_summary'),
     path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
     path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
     path('process_quantity/', views.process_quantity, name='process_quantity'),
] 

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from shop import views as auth_views


app_name='mysite'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('blog/',include('blog.urls')),
    path('payment/',include('payment.urls')),
    path('cart/',include('Cart.urls')),
    path('login/', auth_views.login_user, name='login'),
    path('logout/', auth_views.logout_user, name='logout'),
    path('register/', auth_views.register_user, name='register'),
    path("ckeditor5/", include('django_ckeditor_5.urls')),   
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) 

mysite/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'
urlpatterns = [
    path('payment_success/', views.payment_success, name = 'payment_success'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_processing/', views.process_order, name='process_order'),
    path('undelivered_dash', views.undelivered_dash, name='undelivered_dash'),
    path('delivered_dash/', views.delivered_dash, name='delivered_dash'),
    path('orders/<int:pk>', views.view_order, name='view_order'),
    path('access_token/', views.access_token, name='access_token'),
    path('stk-push/', views.stk_push, name='stk_push')
]

mysite/shop/urls.py
from django.urls import path
from . import views


app_name='shop'
urlpatterns = [
    path('',views.home, name = 'home'),
    path('product/<int:pk>', views.product, name = "product"),
    path('category/<str:cat>', views.category, name = "category"),
    path('offers/', views.offers, name = "offers"),
    path('condition/<str:cat>', views.condition, name = "condition"),
    # path('sub_category/<str:cat>', views.sub_category, name = "sub_category"),
    path('update_user/', views.update_user, name='update_user'),
    path('update_password/', views.update_password, name='update_password'),
    path('update_info/', views.update_info, name='update_info'),
    path('search/', views.search, name='search'),
    path('account_info/', views.account_info, name='account_info'),
    path('product/<int:pk>/add_review', views.add_review, name='add_review'),
    path('product/<int:pk>/remove_review', views.remove_review, name='remove_review'),
    path('favourites/', views.favourites, name='favourites'),
    path('process_email/', views.process_email, name='process_email'),
] 

mysite/Cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
from django.db.models import Sum

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Other cart-related fields

    def total_quantity(self):
        # Calculate the total quantity of items in the cart
        total_quantity = CartItem.objects.aggregate(total=Sum('quantity'))['total']
        return total_quantity if total_quantity is not None else 0

    def total_price_sum(self):
        # Calculate the total price of items in the cart
        total_price = self.items.aggregate(total=Sum(models.F('quantity') * models.F('product__price')))['total']
        return total_price if total_price is not None else 0

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, null = True, blank=True)
    # Other item-related fields

     # Define a method to calculate the total price for this item
    def total_price(self):
        return self.quantity * self.product.price

     # Define a method to calculate the total quantity
    def price_sum(self):
        # Calculate the total price of quantity of this items in the cart
        price = self.cart.items.aggregate(total=models.Sum('product.price'))['total']
        return price 

mysite/Cart/forms.py
from django import forms
# from .models import CartItem
# from  .shop import Product

# product_quantity=Product.models(in_stock)
# class cartAdd(froms.ModelField):
#     quantity=forms.TypedChoiceField(choices=product_quantity, coerce=int)

class QuantityForm(forms.Form):
    quant = forms.IntegerField(min_value=1, label='Quantity', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Phone'}), required=False)

mysite/Cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
# from .cart import Cart
from .forms import QuantityForm
from shop.models import Product
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import CartItem, Cart

def process_quantity(request):
    if request.method == 'POST':
        # product = get_object_or_404(Product, id=product_id)
        product_id = request.POST.get('product_id')
        quant = request.POST.get('quant', '')
        return redirect(request.META.get('HTTP_REFERER', '/'))

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, product=product)

    if request.method == 'POST':
        quant = request.POST.get('quant', '')
        try:
            if quant:
                quantity = int(quant)
            else:
                quantity = int(request.POST.get('quantity', 1))
        except ValueError:
            messages.error(request, 'Invalid quantity value. Please enter a valid number.')
            return redirect(request.META.get('HTTP_REFERER', '/'))

        maximum = product.in_stock
        if quantity > maximum:
            messages.error(request, f'Reduce the quantity. Only {maximum} items in stock.')
            return redirect(request.META.get('HTTP_REFERER', '/'))

        # If the item already exists in the cart, update its quantity
        if not item_created:
            cart_item.quantity += quantity  # Increase quantity by the submitted quantity
        else:
            cart_item.quantity = quantity  # Set quantity to the submitted quantity

        cart_item.save()
        messages.success(request, f'{product.name} {"added to" if item_created else "updated in"} the cart.')
    else:
        messages.error(request, "Invalid form submission")

    return redirect(request.META.get('HTTP_REFERER', '/'))  # Redirect to the previous page       
        


def cart_summary(request):
    # cart = Cart.objects.get(user=request.user)
    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user)
        return render(request, 'cart_summary.html', {'cart': cart})
    else:
        # Handle the case where the user is not logged in
        return redirect('shop:home')


def cart_remove(request, product_id):
    cart = Cart.objects.get(user=request.user)
    item = CartItem.objects.get(cart=cart, product_id=product_id)
    item.delete()
    return redirect('Cart:cart_summary')


# Create your views here.
# def cart_info(request):
#		return render (request, "cart_info.html", {})



# @login_required
# def item_clear(request, id):


# @login_required
# def cart_clear(request):
#     cart = Cart(request)
#     cart.clear()
#     return redirect("cart_detail")

mysite/Cart/templates/cart_summary.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
 <h3 class="fw-bold text-primary text-center">Your shopping cart</h3> 
{% endblock %}
{% block content %}
<h2 class="fw-bold text-primary-emphasis my-1 text-center">Your shopping cart</h2>
<table class="table">
    <thead>
        <tr class="text-primary fs-6 fs-bg-4">
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
    {% for item in cart.items.all %}
        <tr class="align-content-center">
            <td>
                <a href="{{ item.product.get_absolute_url }} {% url 'shop:product' item.product.id %}">
                    <img src="{% if item.product.image %}{{ item.product.image.url }}
                    {% else %}{% static 'img/edit.png' %}{% endif %}">
                </a>
            </td>
            <td class="fw-bolder">{{ item.product.name }}</td>
            <td class="fw-bolder">{{ item.quantity }}</td>
            <td class="">
                <form action="{% url 'Cart:cart_remove' item.product.id %}" method="post">
                    <input type="submit" value="Remove" class='btn btn-primary container-fluid p-0'>
                    {% csrf_token %}
                </form>
            </td>
            <td class="num">ksh {{ item.product.price }}</td>
            <td class="num">ksh {{ item.total_price }}</td>
        </tr>
    {% endfor %}    
        <tr class="total">
            <td></td>
            <td>Total</td>
            <td>{{ cart.total_quantity }}</td>
            <td> Total </td>
            <td>{{ cart.price_sum }} </td>
            <td class="fw-bolder" >Ksh {{ cart.total_price_sum }}</td>
        </tr>
    </tbody>
</table>
<p class="text-right d-flex">
<a href="{% url 'shop:home' %}" class="button
light">Continue shopping</a>
<a href="{% url 'payment:checkout' %}" class="btn btn-success">Checkout</a>
</p>
{% endblock %}

<td>
    <p>p>
    <form action="{% url 'Cart:add_to_cart' product.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Add to Cart">
    </form>
</td>